import type { CreateHabitInput } from "../types";

export const SEEDED_HABITS: (CreateHabitInput & { id: string; targetDaysPerWeek: number })[] = [
  {
    id: "habit-1",
    title: "Code Practice",
    description: "Daily algorithms, open source work, or architecture practice.",
    category: "Productivity",
    color: "violet",
    icon: "Code2",
    frequency: "daily",
    targetDaysPerWeek: 7,
  },
  {
    id: "habit-2",
    title: "Read",
    description: "Read 20 pages of technical books, essays, or non-fiction.",
    category: "Learning",
    color: "blue",
    icon: "BookOpen",
    frequency: "daily",
    targetDaysPerWeek: 7,
  },
  {
    id: "habit-3",
    title: "Exercise",
    description: "Morning workout, gym, running, or stretching session.",
    category: "Fitness",
    color: "emerald",
    icon: "Dumbbell",
    frequency: "daily",
    targetDaysPerWeek: 5,
  },
  {
    id: "habit-4",
    title: "Drink Water",
    description: "Stay hydrated throughout the day: 2.5–3 liters goal.",
    category: "Health",
    color: "blue",
    icon: "Droplets",
    frequency: "daily",
    targetDaysPerWeek: 7,
  },
  {
    id: "habit-5",
    title: "Sleep 8hrs",
    description: "Maintain a calm sleep schedule with ≥8 hours rest.",
    category: "Health",
    color: "pink",
    icon: "Moon",
    frequency: "daily",
    targetDaysPerWeek: 7,
  },
  {
    id: "habit-6",
    title: "Eat Healthy",
    description: "Balanced nutrition, whole foods, minimal processed sugars.",
    category: "Health",
    color: "amber",
    icon: "Apple",
    frequency: "daily",
    targetDaysPerWeek: 7,
  },
];
